name: pattern_matching
description: A simple way to have a (rather primitive) pattern matching functionality in Dart.

version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
